name: Update Wiki Docs

on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  update-wiki:
    name: Update Wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
          
      - name: Build  Wiki Docs
        run: cd ci && ./build.cmd ProcessFilesForWiki
          
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "ci/_temp_GHWiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}