name: Update Readme Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      readmeVersion:
        description: 'Target Readme Version, like `v2022.2.2`'
        required: true
        type: string
        default: 'v2022.4.2'

jobs:
  update-rdme:
    name: Update Readme Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Build and Push Readme Docs
        run: cd ci && ./build.cmd PushReadmeUpdates
        env:
          ReadmeAPIKey: ${{ secrets.READMEAPIKEY }}
          GithubToken: ${{ secrets.GH_PAT }}
          NotionDB: ${{ secrets.NOTION_DB }}
          NotionSecret: ${{ secrets.NOTION_SECRET }}
